'use strict';
const STORAGE_KEY='aftercare.pathway.v5';
const $=id=>document.getElementById(id);
const routes=['today','care-team','profile'];
const icons={home:'<svg viewBox="0 0 24 24"><path d="M3 11.5 12 4l9 7.5"/><path d="M5.5 10.5V20h13v-9.5"/><path d="M9.5 20v-6h5v6"/></svg>',users:'<svg viewBox="0 0 24 24"><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75"/></svg>',user:'<svg viewBox="0 0 24 24"><circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/></svg>',phone:'<svg viewBox="0 0 24 24"><path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6A19.79 19.79 0 0 1 2.12 4.18 2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72c.12.9.33 1.78.62 2.63a2 2 0 0 1-.45 2.11L8 9.73a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45c.85.29 1.73.5 2.63.62A2 2 0 0 1 22 16.92z"/></svg>'};
document.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=icons[el.dataset.icon]||'');
const localDate=(d=new Date())=>[d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-');
const emptyState=()=>({onboarded:false,profile:{firstName:'',procedure:'',dischargeDate:''},care:{teamName:'',phone:''},items:[],completed:{},healthLog:[],painLog:[],symptomLog:[],vitals:[],questions:'',prnLog:[],photos:[]});
function load(){try{const raw=localStorage.getItem(STORAGE_KEY),saved=raw?JSON.parse(raw):{};return{...emptyState(),...saved,profile:{...emptyState().profile,...(saved.profile||{})},care:{...emptyState().care,...(saved.care||{})},items:Array.isArray(saved.items)?saved.items:[],completed:saved.completed&&typeof saved.completed==='object'?saved.completed:{},healthLog:Array.isArray(saved.healthLog)?saved.healthLog:[],painLog:Array.isArray(saved.painLog)?saved.painLog:[],symptomLog:Array.isArray(saved.symptomLog)?saved.symptomLog:[],vitals:Array.isArray(saved.vitals)?saved.vitals:[],prnLog:Array.isArray(saved.prnLog)?saved.prnLog:[],photos:Array.isArray(saved.photos)?saved.photos:[]}}catch{return emptyState()}}
let state=load(),selectedDate=localDate(),activeRoute='today',wizardStep=1,statusTimer,selectedPain=null;
function save(msg){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state));if(msg)notice(msg)}catch{notice('This browser could not save your changes.')}}
function notice(msg){clearTimeout(statusTimer);$('status').textContent=msg;$('status').hidden=false;statusTimer=setTimeout(()=>$('status').hidden=true,3200)}
function calendarDay(v){if(!/^\d{4}-\d{2}-\d{2}$/.test(v))return NaN;const[y,m,d]=v.split('-').map(Number),dt=new Date(Date.UTC(y,m-1,d));return dt.getUTCFullYear()===y&&dt.getUTCMonth()===m-1&&dt.getUTCDate()===d?dt.getTime()/86400000:NaN}
function dateFromISO(v){const[y,m,d]=v.split('-').map(Number);return new Date(y,m-1,d)}
function addDays(v,n){const d=dateFromISO(v);d.setDate(d.getDate()+n);return localDate(d)}
function formatDate(v,opts={weekday:'short',month:'short',day:'numeric'}){return new Intl.DateTimeFormat('en-US',opts).format(dateFromISO(v))}
function pathwayDay(date){const diff=calendarDay(date)-calendarDay(state.profile.dischargeDate);return Number.isFinite(diff)?diff+1:null}
function showScreen(id){['welcome','setup','workspace'].forEach(x=>$(x).hidden=x!==id);window.scrollTo(0,0)}
function showWizard(step){wizardStep=step;[1,2,3].forEach(n=>$(`wizard-${n}`).hidden=n!==step);$('wizard-step-label').textContent=`Step ${step} of 3`;$('wizard-progress').style.width=`${step/3*100}%`;renderSetupLists();window.scrollTo(0,0)}
function itemIcon(type){return type==='medication'?'💊':type==='appointment'?'📅':'🩺'}
function itemTypeLabel(type){return type==='medication'?'Medication':type==='appointment'?'Appointment':'Care Task'}
function itemLabel(item){return `${item.title}${item.dose?` · ${item.dose}`:''}`}
function frequencyLabel(v){return({once:'Once',daily:'Daily',twice:'2x daily',three:'3x daily',q6h:'Every 6 hours'})[v]||v}
function updateDoseVisibility(){const f=$('item-form'),med=f.elements.type.value==='medication';$('dose-label').hidden=!med;$('med-safety-hint').hidden=!med;if(!med)f.elements.dose.value=''}
function renderSetupLists(){const med=$('wizard-med-list'),care=$('wizard-care-list');med.replaceChildren();care.replaceChildren();state.items.forEach(item=>{const row=document.createElement('div');row.className='setup-row';const icon=document.createElement('span');icon.className=`setup-icon ${item.type}`;icon.textContent=itemIcon(item.type);const body=document.createElement('div');body.innerHTML=`<strong>${itemLabel(item)}</strong><small>${itemTypeLabel(item.type)} · ${frequencyLabel(item.frequency)} · ${item.time}</small>`;const actions=document.createElement('div');actions.className='setup-actions';const edit=document.createElement('button');edit.type='button';edit.className='edit-item';edit.textContent='Edit';edit.onclick=()=>openItemDialog(item.type,true,item.id);const del=document.createElement('button');del.type='button';del.className='remove-item';del.textContent='Remove';del.onclick=()=>{state.items=state.items.filter(x=>x.id!==item.id);renderSetupLists()};actions.append(edit,del);row.append(icon,body,actions);(item.type==='medication'?med:care).append(row)})}
function openItemDialog(defaultType='medication',forWizard=false,editId=''){const f=$('item-form');f.reset();f.dataset.wizard=forWizard?'1':'0';f.dataset.editId=editId||'';const item=editId?state.items.find(x=>x.id===editId):null;if(item){f.elements.type.value=item.type;f.elements.title.value=item.title;f.elements.dose.value=item.dose||'';f.elements.startDate.value=item.startDate;f.elements.time.value=item.time;f.elements.frequency.value=item.frequency;$('item-title').textContent='Edit item';$('item-submit').textContent='Save Changes'}else{f.elements.type.value=defaultType;f.elements.startDate.value=state.profile.dischargeDate||selectedDate||localDate();f.elements.time.value='08:00';f.elements.frequency.value='once';$('item-title').textContent='New item';$('item-submit').textContent='Add to Timeline'}updateDoseVisibility();$('item-dialog').showModal();f.elements.title.focus()}
function timesFor(item){if(item.frequency==='twice')return['08:00','20:00'];if(item.frequency==='three')return['08:00','14:00','20:00'];if(item.frequency==='q6h'){const[h,m]=item.time.split(':').map(Number),out=[];for(let i=0;i<4;i++){const total=(h*60+m+i*360)%1440;out.push(`${String(Math.floor(total/60)).padStart(2,'0')}:${String(total%60).padStart(2,'0')}`)}return out}return[item.time]}
function occurs(item,date){const start=calendarDay(item.startDate),target=calendarDay(date);if(!Number.isFinite(start)||!Number.isFinite(target)||target<start)return false;if(item.frequency==='once')return target===start;return true}
function currentTasks(){const tasks=[];state.items.forEach(item=>{if(!occurs(item,selectedDate))return;timesFor(item).forEach(time=>{const key=`${selectedDate}:${item.id}:${time}`;tasks.push({key,itemId:item.id,time,type:item.type,title:itemLabel(item),done:!!state.completed[key],symbol:itemIcon(item.type)})})});state.prnLog.filter(x=>x.date===selectedDate).forEach(x=>tasks.push({key:`prn:${x.id}`,itemId:'',time:x.time,type:'prn',title:`${x.title}${x.dose?` · ${x.dose}`:''}`,done:true,symbol:'💊'}));return tasks.sort((a,b)=>a.time.localeCompare(b.time)||a.title.localeCompare(b.title))}
function toggleTask(task){if(task.type==='prn')return;state.completed[task.key]=!task.done;save(task.done?'Marked not complete':'Marked complete');renderToday()}
function renderDateStrip(){const strip=$('date-strip');strip.replaceChildren();for(let i=-2;i<=4;i++){const date=addDays(selectedDate,i),b=document.createElement('button');b.className='week-day';b.type='button';b.setAttribute('role','option');b.setAttribute('aria-selected',String(date===selectedDate));const today=date===localDate(),label=today?'Today':formatDate(date,{weekday:'short'});b.innerHTML=`<span>${label}</span><strong>${formatDate(date,{day:'numeric'})}</strong>`;b.onclick=()=>{selectedDate=date;selectedPain=null;renderToday()};strip.append(b);if(date===selectedDate)setTimeout(()=>b.scrollIntoView({behavior:'smooth',inline:'center',block:'nearest'}),0)}}
const timeGroups=[{name:'Morning',icon:'☀️',from:5,to:12},{name:'Midday',icon:'◐',from:12,to:17},{name:'Evening',icon:'🌤️',from:17,to:22},{name:'Night',icon:'🌙',from:22,to:29}];
function hourFor(time){return Number((time||'00:00').split(':')[0])}
function inGroup(task,group){let h=hourFor(task.time);if(group.name==='Night'&&h<5)h+=24;return h>=group.from&&h<group.to}
function renderTimeline(){const root=$('day-groups');root.replaceChildren();const tasks=currentTasks();if(!tasks.length){const empty=document.createElement('section');empty.className='empty-day';empty.innerHTML='<strong>Nothing scheduled for this day.</strong><p>Add only the medications, care tasks and appointments that belong to your plan.</p><button type="button">Add first item</button>';empty.querySelector('button').onclick=()=>openItemDialog('medication',false);root.append(empty);return}timeGroups.forEach(group=>{const groupTasks=tasks.filter(t=>inGroup(t,group));if(!groupTasks.length)return;const section=document.createElement('section');section.className='time-block';const head=document.createElement('div');head.className='time-block-header';head.innerHTML=`<span aria-hidden="true">${group.icon}</span><h3>${group.name}</h3>`;const items=document.createElement('div');items.className='time-items';groupTasks.forEach(t=>{const card=document.createElement('article');card.className=`senior-task${t.done?' done':''}`;card.dataset.type=t.type;const icon=document.createElement('span');icon.className='senior-task-icon';icon.textContent=t.symbol;const main=document.createElement('button');main.type='button';main.className='senior-task-main';main.innerHTML=`<time>${new Intl.DateTimeFormat('en-US',{hour:'numeric',minute:'2-digit'}).format(new Date(`2000-01-01T${t.time}`))}</time><strong>${t.title}</strong><small>${t.type==='prn'?'As needed medication':itemTypeLabel(t.type)}${t.type==='prn'?' · logged as taken':''}</small>`;if(t.type!=='prn'){main.setAttribute('aria-label',`Edit ${t.title}`);main.onclick=()=>{const source=state.items.find(x=>x.id===t.itemId);if(source)openItemDialog(source.type,false,source.id)}}else main.disabled=true;const done=document.createElement('button');done.type='button';done.className='task-done-button';done.textContent=t.type==='prn'?'Logged':t.done?'Done ✓':'Done';done.setAttribute('aria-pressed',String(t.done));if(t.type==='prn')done.disabled=true;else done.onclick=()=>toggleTask(t);card.append(icon,main,done);items.append(card)});section.append(head,items);root.append(section)})}
function renderProgress(){const tasks=currentTasks().filter(t=>t.type!=='prn'),done=tasks.filter(t=>t.done).length,total=tasks.length,p=total?Math.round(done/total*100):0;$('progress-text').textContent=`${done} of ${total} done`;$('progress-bar').style.width=`${p}%`}
function timeGreeting(){const h=new Date().getHours();return h<12?'Good morning':h<18?'Good afternoon':'Good evening'}
function latestPain(date){return[...state.painLog].reverse().find(x=>x.date===date)||null}
function renderPain(){const entry=latestPain(selectedDate);document.querySelectorAll('[data-pain]').forEach(b=>b.setAttribute('aria-pressed',String(selectedPain!==null?Number(b.dataset.pain)===selectedPain:entry&&Number(b.dataset.pain)===entry.value)));const saved=$('pain-saved');saved.hidden=!entry;if(entry)saved.textContent=`✓ Pain ${entry.value}/10 saved at ${entry.time}.`}
function renderToday(){const d=pathwayDay(selectedDate),today=selectedDate===localDate();$('recovery-day').textContent=d&&d>=1?`Recovery Day ${d}`:'Pre-discharge';$('today-title').textContent=today?`${timeGreeting()}, ${state.profile.firstName}`:formatDate(selectedDate,{weekday:'long'});$('today-date').textContent=`${formatDate(selectedDate,{month:'long',day:'numeric',year:'numeric'})} · ${state.profile.procedure}`;renderDateStrip();renderPain();renderTimeline();renderProgress();$('doctor-questions').value=state.questions||''}
function renderCare(){const f=$('care-form');f.elements.teamName.value=state.care.teamName||'';f.elements.phone.value=state.care.phone||'';const n=(state.care.phone||'').replace(/[^+\d]/g,''),a=$('call-team');a.hidden=!n;if(n)a.href=`tel:${n}`;a.textContent=state.care.teamName?`Call ${state.care.teamName}`:'Call care team'}
function callCareTeam(){const n=(state.care.phone||'').replace(/[^+\d]/g,'');if(n){location.href=`tel:${n}`;return}navigate('care-team');notice('Add your care team phone number first.')}
function renderTrend(){const list=$('trend-list'),graph=$('trend-graph'),empty=$('trend-empty');list.replaceChildren();graph.replaceChildren();const pains=[...state.painLog].sort((a,b)=>a.timestamp.localeCompare(b.timestamp)).slice(-10);const symptoms=[...state.symptomLog].sort((a,b)=>b.timestamp.localeCompare(a.timestamp)).slice(0,5);empty.hidden=!!(pains.length||symptoms.length);if(pains.length){const w=300,h=90,pad=14,pts=pains.map((e,i)=>({x:pains.length===1?w/2:pad+i*((w-pad*2)/(pains.length-1)),y:pad+(e.value/10)*(h-pad*2),e}));graph.innerHTML=`<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="Pain trend"><path d="${pts.map((p,i)=>`${i?'L':'M'}${p.x},${p.y}`).join(' ')}" fill="none" stroke="#405E78" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/>${pts.map(p=>`<circle cx="${p.x}" cy="${p.y}" r="5" fill="#6F8FAF"/>`).join('')}</svg>`;[...pains].reverse().forEach(e=>{const r=document.createElement('div');r.className='trend-entry';r.innerHTML=`<span class="trend-dot" style="background:#6F8FAF"></span><div><strong>Pain ${e.value}/10</strong><small>${formatDate(e.date,{month:'short',day:'numeric'})}</small></div><time>${e.time}</time>`;list.append(r)})}symptoms.forEach(e=>{const r=document.createElement('div');r.className='trend-entry';r.innerHTML=`<span class="trend-dot" style="background:#D6A85F"></span><div><strong>Symptom note</strong><small>${e.note}</small></div><time>${formatDate(e.date,{month:'short',day:'numeric'})}</time>`;list.append(r)})}
function renderPhotos(){const wrap=$('photo-journal');wrap.replaceChildren();state.photos.forEach(p=>{const d=document.createElement('div');d.className='photo-entry';const img=document.createElement('img');img.src=p.data;img.alt=`Wound journal photo from ${p.date}`;const del=document.createElement('button');del.type='button';del.textContent='×';del.onclick=()=>{state.photos=state.photos.filter(x=>x.id!==p.id);save('Photo removed');renderPhotos()};d.append(img,del);wrap.append(d)})}
function renderProfile(){const f=$('profile-form');f.elements.firstName.value=state.profile.firstName;f.elements.procedure.value=state.profile.procedure;f.elements.dischargeDate.value=state.profile.dischargeDate;renderTrend();renderPhotos()}
function navigate(route){if(!state.onboarded)return;activeRoute=route;routes.forEach(id=>$(id).hidden=id!==route);document.querySelectorAll('.bottom-nav button').forEach(b=>b.dataset.route===route?b.setAttribute('aria-current','page'):b.removeAttribute('aria-current'));if(route==='today')renderToday();if(route==='care-team')renderCare();if(route==='profile')renderProfile();window.scrollTo(0,0)}
function completeSetup(){state.onboarded=true;selectedDate=localDate();save();showScreen('workspace');navigate('today')}
function shareSummary(){const recentPain=[...state.painLog].slice(-5),recentVitals=[...state.vitals].slice(-3),done=Object.values(state.completed).filter(Boolean).length,text=[`Aftercare progress for ${state.profile.firstName}`,`Procedure: ${state.profile.procedure}`,`Discharge: ${state.profile.dischargeDate}`,`Completed timeline items: ${done}`,recentPain.length?'Recent pain check-ins:':'',...recentPain.map(e=>`${e.date} ${e.time}: pain ${e.value}/10`),recentVitals.length?'Recent recorded vitals:':'',...recentVitals.map(e=>`${e.date} ${e.time}: ${[e.temperature&&`Temp ${e.temperature}`,e.bloodPressure&&`BP ${e.bloodPressure}`,e.pulse&&`Pulse ${e.pulse}`].filter(Boolean).join(', ')}`),state.questions?`Questions for doctor: ${state.questions}`:''].filter(Boolean).join('\n');if(navigator.share)navigator.share({title:'Aftercare Progress',text}).catch(()=>{});else{navigator.clipboard?.writeText(text);notice('Progress summary copied to clipboard.')}}
$('start').onclick=()=>{showScreen('setup');showWizard(1)};
$('procedure-form').onsubmit=e=>{e.preventDefault();const f=e.currentTarget,firstName=f.elements.firstName.value.trim(),procedure=f.elements.procedure.value,dischargeDate=f.elements.dischargeDate.value;if(!firstName||!procedure||!Number.isFinite(calendarDay(dischargeDate)))return notice('Complete all procedure details.');state.profile={firstName,procedure,dischargeDate};showWizard(2)};
$('wizard-add-med').onclick=()=>openItemDialog('medication',true);$('wizard-add-care').onclick=()=>openItemDialog('care',true);$('to-care').onclick=()=>showWizard(3);$('skip-meds').onclick=()=>showWizard(3);$('skip-care').onclick=completeSetup;document.querySelectorAll('[data-wizard-back]').forEach(b=>b.onclick=()=>showWizard(Number(b.dataset.wizardBack)));$('complete-setup').onclick=completeSetup;
$('add-item').onclick=()=>openItemDialog('medication',false);$('item-form').elements.type.addEventListener('change',updateDoseVisibility);
$('item-form').onsubmit=e=>{e.preventDefault();const f=e.currentTarget,d=Object.fromEntries(new FormData(f)),editId=f.dataset.editId||'',type=d.type;const item={id:editId||crypto.randomUUID(),type,title:d.title.trim(),dose:type==='medication'?(d.dose||'').trim():'',startDate:d.startDate,time:d.time,frequency:d.frequency,frequencyLabel:frequencyLabel(d.frequency)};if(!item.title||!Number.isFinite(calendarDay(item.startDate))||!/^([01]\d|2[0-3]):[0-5]\d$/.test(item.time))return notice('Complete the required fields.');if(editId){const idx=state.items.findIndex(x=>x.id===editId);if(idx>=0)state.items[idx]=item}else state.items.push(item);$('item-dialog').close();renderSetupLists();if(f.dataset.wizard!=='1'){save(editId?'Item updated':'Item added');selectedDate=item.startDate;renderToday()}};
$('log-prn').onclick=()=>{const f=$('prn-form');f.reset();f.elements.time.value=new Date().toTimeString().slice(0,5);$('prn-dialog').showModal()};$('prn-form').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));state.prnLog.push({id:crypto.randomUUID(),date:selectedDate,time:d.time,title:d.title.trim(),dose:(d.dose||'').trim()});save('As-needed medication logged');$('prn-dialog').close();renderToday()};
document.querySelectorAll('[data-pain]').forEach(b=>b.onclick=()=>{selectedPain=Number(b.dataset.pain);renderPain()});$('save-pain').onclick=()=>{if(selectedPain===null)return notice('Choose a pain level first.');const now=new Date(),time=now.toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'}),timestamp=`${selectedDate}T${String(now.getHours()).padStart(2,'0')}:${String(now.getMinutes()).padStart(2,'0')}:${String(now.getSeconds()).padStart(2,'0')}`;state.painLog.push({id:crypto.randomUUID(),date:selectedDate,value:selectedPain,time,timestamp});save('Pain check-in saved');selectedPain=null;renderPain()};
$('report-symptoms').onclick=()=>{$('symptom-form').reset();$('symptom-dialog').showModal()};$('symptom-form').onsubmit=e=>{e.preventDefault();const note=e.currentTarget.elements.note.value.trim();if(!note)return;const now=new Date(),time=now.toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'}),timestamp=`${selectedDate}T${String(now.getHours()).padStart(2,'0')}:${String(now.getMinutes()).padStart(2,'0')}:${String(now.getSeconds()).padStart(2,'0')}`;state.symptomLog.push({id:crypto.randomUUID(),date:selectedDate,note,time,timestamp});save('Symptom note saved');$('symptom-dialog').close()};
$('add-vitals').onclick=()=>{$('vitals-form').reset();$('vitals-dialog').showModal()};$('vitals-form').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));if(!d.temperature&&!d.bloodPressure&&!d.pulse)return notice('Enter at least one value.');const now=new Date(),time=now.toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'});state.vitals.push({id:crypto.randomUUID(),date:selectedDate,time,temperature:(d.temperature||'').trim(),bloodPressure:(d.bloodPressure||'').trim(),pulse:(d.pulse||'').trim(),timestamp:now.toISOString()});save('Vitals saved');$('vitals-dialog').close()};
$('today-call').onclick=callCareTeam;$('help-call').onclick=callCareTeam;$('symptom-care-call').onclick=()=>{$('symptom-dialog').close();callCareTeam()};
$('save-questions').onclick=()=>{state.questions=$('doctor-questions').value.trim();save('Questions saved')};$('share-progress').onclick=shareSummary;
$('wound-photo').onchange=e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>3_000_000){notice('Please choose a photo under 3 MB.');e.target.value='';return}const reader=new FileReader();reader.onload=()=>{state.photos.push({id:crypto.randomUUID(),date:localDate(),data:reader.result});save('Photo saved on this device');renderPhotos();e.target.value=''};reader.readAsDataURL(file)};
$('care-form').onsubmit=e=>{e.preventDefault();const teamName=e.currentTarget.elements.teamName.value.trim(),phone=e.currentTarget.elements.phone.value.trim();if(!teamName||!phone)return notice('Enter a care team name and phone number.');state.care={teamName,phone};save('Care team saved');renderCare()};
$('profile-form').onsubmit=e=>{e.preventDefault();const f=e.currentTarget,firstName=f.elements.firstName.value.trim(),procedure=f.elements.procedure.value.trim(),dischargeDate=f.elements.dischargeDate.value;if(!firstName||!procedure||!Number.isFinite(calendarDay(dischargeDate)))return notice('Complete all profile fields.');state.profile={firstName,procedure,dischargeDate};save('Profile updated');renderProfile()};
document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>navigate(b.dataset.route));$('critical-care').onclick=()=>{$('critical-dialog').close();callCareTeam()};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());
if(state.onboarded){showScreen('workspace');navigate('today')}else{showScreen('welcome')}
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));