'use strict';
const STORAGE_KEY='aftercare.pathway.v5';
const INTRO_KEY='aftercare.welcome.clinical.v1';
const $=id=>document.getElementById(id);
const routes=['today','medications','care-team'];
const iconSvg={
  home:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3.5 11.5 12 4l8.5 7.5"/><path d="M5.5 10.5V20h13v-9.5"/><path d="M9.5 20v-6h5v6"/></svg>',
  pill:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M8.5 4.5a4.95 4.95 0 0 1 7 0l4 4a4.95 4.95 0 0 1-7 7l-4-4a4.95 4.95 0 0 1 0-7Z"/><path d="m9.5 12.5 5-5"/></svg>',
  phone:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M22 16.9v3a2 2 0 0 1-2.2 2 19.8 19.8 0 0 1-8.6-3.1 19.5 19.5 0 0 1-6-6A19.8 19.8 0 0 1 2.1 4.2 2 2 0 0 1 4.1 2h3a2 2 0 0 1 2 1.7c.1.9.3 1.8.6 2.6a2 2 0 0 1-.4 2.1L8 9.7a16 16 0 0 0 6 6l1.3-1.3a2 2 0 0 1 2.1-.4c.8.3 1.7.5 2.6.6a2 2 0 0 1 2 2.3Z"/></svg>'
};
document.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=iconSvg[el.dataset.icon]||'');

const emptyState=()=>({onboarded:false,profile:{firstName:'',procedure:'',dischargeDate:''},care:{teamName:'',phone:'',clinicName:'',clinicPhone:''},items:[],completed:{},painLog:[],prnLog:[],healthLog:[],symptomLog:[],vitals:[],questions:'',photos:[]});
function load(){try{const raw=localStorage.getItem(STORAGE_KEY),saved=raw?JSON.parse(raw):{};const base=emptyState();return{...base,...saved,profile:{...base.profile,...(saved.profile||{})},care:{...base.care,...(saved.care||{})},items:Array.isArray(saved.items)?saved.items:[],completed:saved.completed&&typeof saved.completed==='object'?saved.completed:{},painLog:Array.isArray(saved.painLog)?saved.painLog:[],prnLog:Array.isArray(saved.prnLog)?saved.prnLog:[]}}catch{return emptyState()}}
let state=load(),selectedDate=localDate(),statusTimer;

function localDate(d=new Date()){return[d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')}
function dateFromISO(v){const[y,m,d]=v.split('-').map(Number);return new Date(y,m-1,d)}
function addDays(v,n){const d=dateFromISO(v);d.setDate(d.getDate()+n);return localDate(d)}
function calendarDay(v){if(!/^\d{4}-\d{2}-\d{2}$/.test(v))return NaN;const[y,m,d]=v.split('-').map(Number),dt=new Date(Date.UTC(y,m-1,d));return dt.getUTCFullYear()===y&&dt.getUTCMonth()===m-1&&dt.getUTCDate()===d?dt.getTime()/86400000:NaN}
function formatDate(v,opts){return new Intl.DateTimeFormat('en-US',opts||{month:'short',day:'numeric'}).format(dateFromISO(v))}
function save(msg){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state));if(msg)notice(msg)}catch{notice('This browser could not save your changes.')}}
function notice(msg){clearTimeout(statusTimer);$('status').textContent=msg;$('status').hidden=false;statusTimer=setTimeout(()=>$('status').hidden=true,2600)}
function pathwayDay(date){const diff=calendarDay(date)-calendarDay(state.profile.dischargeDate);return Number.isFinite(diff)?diff+1:null}
function showScreen(id){['welcome','setup','workspace'].forEach(x=>$(x).hidden=x!==id);window.scrollTo(0,0)}
function showWizard(step){[1,2,3].forEach(n=>$(`wizard-${n}`).hidden=n!==step);$('wizard-step-label').textContent=`Step ${step} of 3`;$('wizard-progress').style.width=`${step/3*100}%`;renderSetupLists();window.scrollTo(0,0)}
function navigate(route){if(!state.onboarded)return;routes.forEach(id=>$(id).hidden=id!==route);document.querySelectorAll('.bottom-nav button').forEach(b=>b.dataset.route===route?b.setAttribute('aria-current','page'):b.removeAttribute('aria-current'));$('fab').hidden=route!=='today';if(route==='today')renderToday();if(route==='medications')renderMedications();if(route==='care-team')renderCare();window.scrollTo(0,0)}

function frequencyLabel(v){return({once:'Once',daily:'Daily',twice:'2x daily',three:'3x daily',q6h:'Every 6 hours'})[v]||v}
function itemTypeLabel(type){return type==='medication'?'Medication':type==='appointment'?'Appointment':'Care task'}
function itemCode(type){return type==='medication'?'Rx':type==='appointment'?'Appt':'Care'}
function itemLabel(item){return `${item.title}${item.dose?` · ${item.dose}`:''}`}
function renderSetupLists(){const med=$('wizard-med-list'),care=$('wizard-care-list');med.replaceChildren();care.replaceChildren();state.items.forEach(item=>{const row=document.createElement('div');row.className='setup-row';const icon=document.createElement('span');icon.className=`setup-icon ${item.type}`;icon.textContent=itemCode(item.type);const body=document.createElement('div');const title=document.createElement('strong');title.textContent=itemLabel(item);const meta=document.createElement('small');meta.textContent=`${itemTypeLabel(item.type)} · ${frequencyLabel(item.frequency)} · ${item.time}`;body.append(title,meta);const actions=document.createElement('div');actions.className='setup-actions';const edit=document.createElement('button');edit.type='button';edit.textContent='Edit';edit.onclick=()=>openItemSheet(item.type,true,item.id);const remove=document.createElement('button');remove.type='button';remove.className='remove-item';remove.textContent='Remove';remove.onclick=()=>{state.items=state.items.filter(x=>x.id!==item.id);renderSetupLists()};actions.append(edit,remove);row.append(icon,body,actions);(item.type==='medication'?med:care).append(row)})}

function setEntryType(type){const form=$('item-form');form.elements.type.value=type;document.querySelectorAll('[data-entry-type]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.entryType===type)));const med=type==='medication';$('dose-label').childNodes[0].nodeValue=med?'Dose / note':'Note';$('med-safety-hint').hidden=!med}
function openItemSheet(defaultType='medication',forWizard=false,editId='',presetTime=''){const form=$('item-form');form.reset();form.dataset.wizard=forWizard?'1':'0';form.dataset.editId=editId||'';const item=editId?state.items.find(x=>x.id===editId):null;if(item){setEntryType(item.type);form.elements.title.value=item.title;form.elements.dose.value=item.dose||'';form.elements.startDate.value=item.startDate;form.elements.time.value=item.time;form.elements.frequency.value=item.frequency;$('item-title').textContent='Edit timeline entry';$('item-submit').textContent='Save changes'}else{setEntryType(defaultType);form.elements.startDate.value=state.profile.dischargeDate||selectedDate||localDate();form.elements.time.value=presetTime||new Date().toTimeString().slice(0,5);form.elements.frequency.value='once';$('item-title').textContent='Add to timeline';$('item-submit').textContent='Save to timeline'}$('item-sheet').showModal();setTimeout(()=>form.elements.title.focus(),80)}

function toMinutes(time){const[h,m]=time.split(':').map(Number);return h*60+m}
function fromMinutes(total){const t=((total%1440)+1440)%1440;return`${String(Math.floor(t/60)).padStart(2,'0')}:${String(t%60).padStart(2,'0')}`}
function timesFor(item){const start=toMinutes(item.time||'08:00');if(item.frequency==='twice')return[fromMinutes(start),fromMinutes(start+720)];if(item.frequency==='three')return[fromMinutes(start),fromMinutes(start+480),fromMinutes(start+960)];if(item.frequency==='q6h')return[0,360,720,1080].map(n=>fromMinutes(start+n));return[item.time]}
function occurs(item,date){const start=calendarDay(item.startDate),target=calendarDay(date);if(!Number.isFinite(start)||!Number.isFinite(target)||target<start)return false;if(item.frequency==='once')return target===start;return true}
function currentTasks(){const tasks=[];state.items.forEach(item=>{if(!occurs(item,selectedDate))return;timesFor(item).forEach(time=>{const key=`${selectedDate}:${item.id}:${time}`;tasks.push({key,itemId:item.id,time,type:item.type,title:itemLabel(item),done:!!state.completed[key]})})});state.prnLog.filter(x=>x.date===selectedDate).forEach(x=>tasks.push({key:`prn:${x.id}`,itemId:'',time:x.time,type:'prn',title:`${x.title}${x.dose?` · ${x.dose}`:''}`,done:true}));return tasks.sort((a,b)=>a.time.localeCompare(b.time)||a.title.localeCompare(b.title))}
function toggleTask(task){if(task.type==='prn')return;state.completed[task.key]=!task.done;save();renderToday()}

function renderDateStrip(){const strip=$('date-strip');strip.replaceChildren();for(let i=-3;i<=3;i++){const date=addDays(selectedDate,i),button=document.createElement('button');button.className='date-day';button.type='button';button.setAttribute('role','option');button.setAttribute('aria-selected',String(date===selectedDate));const label=document.createElement('span');label.textContent=date===localDate()?'Today':formatDate(date,{weekday:'narrow'});const num=document.createElement('strong');num.textContent=formatDate(date,{day:'numeric'});button.append(label,num);button.onclick=()=>{selectedDate=date;renderToday()};strip.append(button)}}
const groups=[{key:'morning',label:'Morning',display:'08:00 AM',from:5,to:12,preset:'08:00'},{key:'midday',label:'Midday',display:'12:30 PM',from:12,to:17,preset:'12:30'},{key:'evening',label:'Evening',display:'06:00 PM',from:17,to:22,preset:'18:00'},{key:'night',label:'Night',display:'10:00 PM',from:22,to:29,preset:'22:00'}];
function taskInGroup(task,group){let h=Number(task.time.split(':')[0]);if(group.key==='night'&&h<5)h+=24;return h>=group.from&&h<group.to}
function renderTask(task){const card=document.createElement('article');card.className=`task-card${task.done?' done':''}`;const icon=document.createElement('span');icon.className='task-icon';icon.textContent=task.type==='prn'?'PRN':itemCode(task.type);const body=document.createElement('button');body.type='button';body.className='task-body';const time=document.createElement('time');time.textContent=new Intl.DateTimeFormat('en-US',{hour:'numeric',minute:'2-digit'}).format(new Date(`2000-01-01T${task.time}`));const title=document.createElement('strong');title.textContent=task.title;body.append(time,title);if(task.itemId)body.onclick=()=>{const source=state.items.find(x=>x.id===task.itemId);if(source)openItemSheet(source.type,false,source.id)};else body.disabled=true;const check=document.createElement('button');check.type='button';check.className='task-check';check.textContent='✓';check.setAttribute('aria-label',task.done?'Mark not complete':'Mark complete');check.setAttribute('aria-pressed',String(task.done));if(task.type==='prn')check.disabled=true;else check.onclick=()=>toggleTask(task);card.append(icon,body,check);return card}
function renderTimeline(){const root=$('timeline');root.replaceChildren();const tasks=currentTasks();groups.forEach(group=>{const section=document.createElement('section');section.className='timeline-section';const dot=document.createElement('span');dot.className='timeline-dot';const head=document.createElement('div');head.className='timeline-section-head';const time=document.createElement('time');time.textContent=group.display;const h=document.createElement('h3');h.textContent=group.label;head.append(time,h);const list=document.createElement('div');list.className='task-list';const matched=tasks.filter(t=>taskInGroup(t,group));if(matched.length)matched.forEach(task=>list.append(renderTask(task)));else{const placeholder=document.createElement('div');placeholder.className='placeholder-card';const text=document.createElement('span');text.textContent='No item scheduled';const add=document.createElement('button');add.type='button';add.textContent='+ Add';add.onclick=()=>openItemSheet('medication',false,'',group.preset);placeholder.append(text,add);list.append(placeholder)}section.append(dot,head,list);root.append(section)})}
function renderProgress(){const tasks=currentTasks().filter(t=>t.type!=='prn'),done=tasks.filter(t=>t.done).length;$('progress-text').textContent=`${done} of ${tasks.length} done`}
function latestPain(date){return[...state.painLog].reverse().find(x=>x.date===date)||null}
function renderPain(){const entry=latestPain(selectedDate);document.querySelectorAll('[data-pain]').forEach(b=>b.setAttribute('aria-pressed',String(entry&&Number(b.dataset.pain)===entry.value)));$('pain-saved').textContent=entry?`Saved ${entry.time}`:''}
function savePain(value){const now=new Date(),time=now.toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'}),timestamp=`${selectedDate}T${String(now.getHours()).padStart(2,'0')}:${String(now.getMinutes()).padStart(2,'0')}:${String(now.getSeconds()).padStart(2,'0')}`;state.painLog.push({id:crypto.randomUUID(),date:selectedDate,value,time,timestamp});save();renderPain()}
function renderToday(){const d=pathwayDay(selectedDate),today=selectedDate===localDate();$('today-title').textContent=today?formatDate(selectedDate,{weekday:'long',month:'long',day:'numeric'}):formatDate(selectedDate,{weekday:'long',month:'long',day:'numeric'});$('today-meta').textContent=`${d&&d>=1?`Recovery day ${d}`:'Pre-discharge'} · ${state.profile.procedure}`;renderDateStrip();renderPain();renderTimeline();renderProgress()}

function renderMedications(){const meds=state.items.filter(x=>x.type==='medication'),list=$('med-list');$('scheduled-med-count').textContent=String(meds.length);$('prn-count').textContent=String(state.prnLog.length);list.replaceChildren();if(!meds.length){const card=document.createElement('div');card.className='med-card';const h=document.createElement('h3');h.textContent='No medications added yet';const p=document.createElement('p');p.textContent='Add medications exactly as listed on your prescription or discharge medication list.';card.append(h,p);list.append(card);return}meds.forEach(item=>{const card=document.createElement('article');card.className='med-card';const top=document.createElement('div');top.className='med-card-top';const body=document.createElement('div');const h=document.createElement('h3');h.textContent=item.title;const p=document.createElement('p');p.textContent=`${item.dose?`${item.dose} · `:''}${frequencyLabel(item.frequency)} · ${item.time}`;body.append(h,p);const edit=document.createElement('button');edit.type='button';edit.textContent='Edit';edit.onclick=()=>openItemSheet('medication',false,item.id);top.append(body,edit);card.append(top);list.append(card)})}

function renderCare(){const care=state.care||{};$('surgeon-name').textContent=care.teamName||'Not configured';$('surgeon-phone').textContent=care.phone||'Add the number from your discharge instructions.';$('clinic-name').textContent=care.clinicName||'Not configured';$('clinic-phone').textContent=care.clinicPhone||'Optional secondary contact.';const f=$('care-form');f.elements.teamName.value=care.teamName||'';f.elements.phone.value=care.phone||'';f.elements.clinicName.value=care.clinicName||'';f.elements.clinicPhone.value=care.clinicPhone||''}
function dial(phone,msg){const n=(phone||'').replace(/[^+\d]/g,'');if(n)location.href=`tel:${n}`;else{navigate('care-team');$('care-edit-wrap').hidden=false;notice(msg)}}
function callSurgeon(){dial(state.care.phone,'Add your surgeon or care team number first.')}
function callClinic(){dial(state.care.clinicPhone,'Add your hospital or clinic number first.')}

function renderQuickMeds(){const wrap=$('quick-med-list');wrap.replaceChildren();state.items.filter(x=>x.type==='medication').slice(0,3).forEach(item=>{const b=document.createElement('button');b.className='quick-med';b.type='button';b.textContent=item.dose?`${item.title} · ${item.dose}`:item.title;b.onclick=()=>{const f=$('prn-form');f.elements.title.value=item.title;f.elements.dose.value=item.dose||''};wrap.append(b)});const custom=document.createElement('button');custom.className='quick-med';custom.type='button';custom.textContent='Custom medication';custom.onclick=()=>{const f=$('prn-form');f.elements.title.value='';f.elements.dose.value='';f.elements.title.focus()};wrap.append(custom)}
function openPrnSheet(){const f=$('prn-form');f.reset();f.elements.time.value=new Date().toTimeString().slice(0,5);renderQuickMeds();$('prn-sheet').showModal()}

$('start').onclick=()=>{localStorage.setItem(INTRO_KEY,'1');if(state.onboarded){showScreen('workspace');navigate('today')}else{showScreen('setup');showWizard(1)}};
$('procedure-form').onsubmit=e=>{e.preventDefault();const f=e.currentTarget,firstName=f.elements.firstName.value.trim(),procedure=f.elements.procedure.value,dischargeDate=f.elements.dischargeDate.value;if(!firstName||!procedure||!Number.isFinite(calendarDay(dischargeDate)))return notice('Complete all procedure details.');state.profile={firstName,procedure,dischargeDate};showWizard(2)};
$('wizard-add-med').onclick=()=>openItemSheet('medication',true);$('wizard-add-care').onclick=()=>openItemSheet('care',true);$('to-care').onclick=()=>showWizard(3);$('skip-meds').onclick=()=>showWizard(3);document.querySelectorAll('[data-wizard-back]').forEach(b=>b.onclick=()=>showWizard(Number(b.dataset.wizardBack)));
function completeSetup(){state.onboarded=true;selectedDate=localDate();save();showScreen('workspace');navigate('today')}
$('skip-care').onclick=completeSetup;$('complete-setup').onclick=completeSetup;

document.querySelectorAll('[data-entry-type]').forEach(b=>b.onclick=()=>setEntryType(b.dataset.entryType));
$('item-form').onsubmit=e=>{e.preventDefault();const f=e.currentTarget,d=Object.fromEntries(new FormData(f)),editId=f.dataset.editId||'',type=d.type,item={id:editId||crypto.randomUUID(),type,title:d.title.trim(),dose:(d.dose||'').trim(),startDate:d.startDate,time:d.time,frequency:d.frequency||'once'};if(!item.title||!Number.isFinite(calendarDay(item.startDate))||!/^([01]\d|2[0-3]):[0-5]\d$/.test(item.time))return notice('Complete the required fields.');if(editId){const i=state.items.findIndex(x=>x.id===editId);if(i>=0)state.items[i]=item}else state.items.push(item);$('item-sheet').close();renderSetupLists();if(f.dataset.wizard!=='1'){save(editId?'Entry updated':'Entry added');selectedDate=item.startDate;renderToday();renderMedications()}};
$('header-add').onclick=()=>openItemSheet('medication',false);$('fab').onclick=()=>openItemSheet('medication',false);$('med-add').onclick=()=>openItemSheet('medication',false);$('log-prn').onclick=openPrnSheet;
$('prn-form').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget)),title=d.title.trim();if(!title)return;state.prnLog.push({id:crypto.randomUUID(),date:selectedDate,time:d.time,title,dose:(d.dose||'').trim(),administration:d.administration||''});save('Medication log saved');$('prn-sheet').close();renderToday();renderMedications()};
document.querySelectorAll('[data-pain]').forEach(b=>b.onclick=()=>savePain(Number(b.dataset.pain)));
$('call-surgeon').onclick=callSurgeon;$('call-clinic').onclick=callClinic;$('care-edit-toggle').onclick=()=>{$('care-edit-wrap').hidden=!$('care-edit-wrap').hidden};
$('care-form').onsubmit=e=>{e.preventDefault();const f=e.currentTarget;state.care={teamName:f.elements.teamName.value.trim(),phone:f.elements.phone.value.trim(),clinicName:f.elements.clinicName.value.trim(),clinicPhone:f.elements.clinicPhone.value.trim()};save('Contacts saved');$('care-edit-wrap').hidden=true;renderCare()};
document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>navigate(b.dataset.route));document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());

const introSeen=localStorage.getItem(INTRO_KEY)==='1';
if(!introSeen){showScreen('welcome');$('start').textContent=state.onboarded?'Continue to Aftercare':'Set up my recovery'}else if(state.onboarded){showScreen('workspace');navigate('today')}else showScreen('welcome');
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));