'use strict';
const STORAGE_KEY='aftercare.pathway.v5';
const $=id=>document.getElementById(id);
const routes=['today','care-team','profile'];
const icons={home:'<svg viewBox="0 0 24 24"><path d="M3 11.5 12 4l9 7.5"/><path d="M5.5 10.5V20h13v-9.5"/><path d="M9.5 20v-6h5v6"/></svg>',users:'<svg viewBox="0 0 24 24"><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75"/></svg>',user:'<svg viewBox="0 0 24 24"><circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/></svg>'};
document.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=icons[el.dataset.icon]||'');
const localDate=(d=new Date())=>[d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-');
const emptyState=()=>({onboarded:false,profile:{firstName:'',procedure:'',dischargeDate:''},care:{teamName:'',phone:''},items:[],completed:{},healthLog:[],painLog:[],vitals:[],questions:'',prnLog:[],photos:[]});
function load(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}');return{...emptyState(),...saved,profile:{...emptyState().profile,...(saved.profile||{})},care:{...emptyState().care,...(saved.care||{})},items:Array.isArray(saved.items)?saved.items:[],completed:saved.completed&&typeof saved.completed==='object'?saved.completed:{},healthLog:Array.isArray(saved.healthLog)?saved.healthLog:[],painLog:Array.isArray(saved.painLog)?saved.painLog:[],vitals:Array.isArray(saved.vitals)?saved.vitals:[],prnLog:Array.isArray(saved.prnLog)?saved.prnLog:[],photos:Array.isArray(saved.photos)?saved.photos:[]}}catch{return emptyState()}}
let state=load(),selectedDate=localDate(),statusTimer,wizardStep=1;
function save(msg){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state));if(msg)notice(msg)}catch{notice('This browser could not save your changes.')}}
function notice(msg){clearTimeout(statusTimer);$('status').textContent=msg;$('status').hidden=false;statusTimer=setTimeout(()=>$('status').hidden=true,3000)}
function calendarDay(v){if(!/^\d{4}-\d{2}-\d{2}$/.test(v))return NaN;const[y,m,d]=v.split('-').map(Number),dt=new Date(Date.UTC(y,m-1,d));return dt.getTime()/86400000}
function dateFromISO(v){const[y,m,d]=v.split('-').map(Number);return new Date(y,m-1,d)}
function addDays(v,n){const d=dateFromISO(v);d.setDate(d.getDate()+n);return localDate(d)}
function formatDate(v,opts={weekday:'short',month:'short',day:'numeric'}){return new Intl.DateTimeFormat('en-US',opts).format(dateFromISO(v))}
function pathwayDay(date){const diff=calendarDay(date)-calendarDay(state.profile.dischargeDate);return Number.isFinite(diff)?diff+1:null}
function showScreen(id){['welcome','setup','workspace'].forEach(x=>$(x).hidden=x!==id);window.scrollTo(0,0)}
function showWizard(step){wizardStep=step;[1,2,3].forEach(n=>$(`wizard-${n}`).hidden=n!==step);$('wizard-step-label').textContent=`Step ${step} of 3`;$('wizard-progress').style.width=`${step/3*100}%`;renderSetupLists();window.scrollTo(0,0)}
function itemIcon(type){return type==='medication'?'💊':type==='appointment'?'📅':'🩺'}
function itemTypeLabel(type){return type==='medication'?'Medication':type==='appointment'?'Appointment':'Care Task'}
function frequencyLabel(v){return({once:'Once',daily:'Daily',twice:'2x daily',three:'3x daily',q6h:'Every 6 hours'})[v]||v}
function itemLabel(item){return `${item.title}${item.dose?` · ${item.dose}`:''}`}
function updateDoseVisibility(){const f=$('item-form'),med=f.elements.type.value==='medication';$('dose-label').hidden=!med;$('med-safety-hint').hidden=!med;if(!med)f.elements.dose.value=''}
function renderSetupLists(){const med=$('wizard-med-list'),care=$('wizard-care-list');med.replaceChildren();care.replaceChildren();state.items.forEach(item=>{const row=document.createElement('div');row.className='setup-row';row.innerHTML=`<span class="setup-icon ${item.type}">${itemIcon(item.type)}</span><div><strong>${itemLabel(item)}</strong><small>${itemTypeLabel(item.type)} · ${frequencyLabel(item.frequency)} · ${item.time}</small></div>`;const a=document.createElement('div');a.className='setup-actions';const edit=document.createElement('button');edit.type='button';edit.textContent='Edit';edit.className='edit-item';edit.onclick=()=>openItemDialog(item.type,true,item.id);const del=document.createElement('button');del.type='button';del.textContent='Remove';del.className='remove-item';del.onclick=()=>{state.items=state.items.filter(x=>x.id!==item.id);renderSetupLists()};a.append(edit,del);row.append(a);(item.type==='medication'?med:care).append(row)})}
function openItemDialog(defaultType='medication',forWizard=false,editId=''){const f=$('item-form');f.reset();f.dataset.wizard=forWizard?'1':'0';f.dataset.editId=editId;const item=editId?state.items.find(x=>x.id===editId):null;if(item){f.elements.type.value=item.type;f.elements.title.value=item.title;f.elements.dose.value=item.dose||'';f.elements.startDate.value=item.startDate;f.elements.time.value=item.time;f.elements.frequency.value=item.frequency;$('item-title').textContent='Edit item';$('item-submit').textContent='Save Changes'}else{f.elements.type.value=defaultType;f.elements.startDate.value=state.profile.dischargeDate||selectedDate||localDate();f.elements.time.value='08:00';f.elements.frequency.value='once';$('item-title').textContent='New item';$('item-submit').textContent='Add to Timeline'}updateDoseVisibility();$('item-dialog').showModal();f.elements.title.focus()}
function timesFor(item){if(item.frequency==='twice')return['08:00','20:00'];if(item.frequency==='three')return['08:00','14:00','20:00'];if(item.frequency==='q6h'){const[h,m]=item.time.split(':').map(Number),out=[];for(let i=0;i<4;i++){const total=(h*60+m+i*360)%1440;out.push(`${String(Math.floor(total/60)).padStart(2,'0')}:${String(total%60).padStart(2,'0')}`)}return out}return[item.time]}
function occurs(item,date){const start=calendarDay(item.startDate),target=calendarDay(date);if(!Number.isFinite(start)||!Number.isFinite(target)||target<start)return false;if(item.frequency==='once')return target===start;return true}
function currentTasks(){const tasks=[];state.items.forEach(item=>{if(!occurs(item,selectedDate))return;timesFor(item).forEach(time=>{const key=`${selectedDate}:${item.id}:${time}`;tasks.push({key,itemId:item.id,time,type:item.type,title:itemLabel(item),done:!!state.completed[key],symbol:itemIcon(item.type)})})});state.prnLog.filter(x=>x.date===selectedDate).forEach(x=>tasks.push({key:`prn:${x.id}`,itemId:'',time:x.time,type:'prn',title:`${x.title}${x.dose?` · ${x.dose}`:''}`,done:true,symbol:'💊'}));return tasks.sort((a,b)=>a.time.localeCompare(b.time)||a.title.localeCompare(b.title))}
function toggleTask(task){if(task.type==='prn')return;state.completed[task.key]=!task.done;save();renderToday()}
function renderDateStrip(){const strip=$('date-strip');strip.replaceChildren();for(let i=-3;i<=3;i++){const date=addDays(selectedDate,i),b=document.createElement('button');b.className='week-day';b.type='button';b.setAttribute('role','option');b.setAttribute('aria-selected',String(date===selectedDate));b.innerHTML=`<span>${date===localDate()?'Today':formatDate(date,{weekday:'short'})}</span><strong>${formatDate(date,{day:'numeric'})}</strong>`;b.onclick=()=>{selectedDate=date;renderToday()};strip.append(b)}}
const timeGroups=[{name:'Morning',icon:'☀️',from:0,to:12},{name:'Midday',icon:'☀️',from:12,to:17},{name:'Evening',icon:'🌙',from:17,to:24}];
function renderTimeline(){const root=$('day-groups');root.replaceChildren();const tasks=currentTasks();if(!tasks.length){const empty=document.createElement('section');empty.className='empty-day';empty.innerHTML='<strong>Nothing scheduled for this day.</strong><p>Add only the medications, care tasks and appointments that belong to your plan.</p><button type="button">Add first item</button>';empty.querySelector('button').onclick=()=>openItemDialog('medication',false);root.append(empty);return}timeGroups.forEach(group=>{const groupTasks=tasks.filter(t=>{const h=Number(t.time.split(':')[0]);return h>=group.from&&h<group.to});if(!groupTasks.length)return;const section=document.createElement('section');section.className='time-block';section.innerHTML=`<div class="time-block-header"><span aria-hidden="true">${group.icon}</span><h3>${group.name}</h3></div><div class="time-items"></div>`;const items=section.querySelector('.time-items');groupTasks.forEach(t=>{const card=document.createElement('article');card.className=`senior-task${t.done?' done':''}`;card.dataset.type=t.type;const icon=document.createElement('span');icon.className='senior-task-icon';icon.textContent=t.symbol;const main=document.createElement('button');main.type='button';main.className='senior-task-main';main.innerHTML=`<time>${new Intl.DateTimeFormat('en-US',{hour:'numeric',minute:'2-digit'}).format(new Date(`2000-01-01T${t.time}`))}</time><strong>${t.title}</strong><small>${t.type==='prn'?'As needed medication':itemTypeLabel(t.type)}</small>`;if(t.type!=='prn')main.onclick=()=>{const src=state.items.find(x=>x.id===t.itemId);if(src)openItemDialog(src.type,false,src.id)};else main.disabled=true;const done=document.createElement('button');done.type='button';done.className='task-done-button';done.textContent=t.type==='prn'?'Logged':t.done?'Done ✓':'Done';done.setAttribute('aria-pressed',String(t.done));if(t.type==='prn')done.disabled=true;else done.onclick=()=>toggleTask(t);card.append(icon,main,done);items.append(card)});root.append(section)})}
function renderProgress(){const tasks=currentTasks().filter(t=>t.type!=='prn'),done=tasks.filter(t=>t.done).length,total=tasks.length,p=total?Math.round(done/total*100):0;$('progress-text').textContent=`${done} of ${total} done`;$('progress-bar').style.width=`${p}%`}
function timeGreeting(){const h=new Date().getHours();return h<12?'Good morning':h<18?'Good afternoon':'Good evening'}
const statusMap={'very-good':{label:'Very good',pain:0},okay:{label:'Okay',pain:3},pain:{label:'In pain',pain:7},critical:{label:'Critical',pain:10}};
function latestStatus(date){return[...state.healthLog].reverse().find(x=>x.date===date&&x.statusV8)||null}
function renderStatus(){const entry=latestStatus(selectedDate);document.querySelectorAll('[data-status]').forEach(b=>b.setAttribute('aria-pressed',String(entry&&b.dataset.status===entry.statusV8)));const saved=$('status-saved');saved.hidden=!entry;if(entry)saved.textContent=`✓ ${statusMap[entry.statusV8]?.label||entry.statusV8} saved at ${entry.time}.`}
function logStatus(status){const meta=statusMap[status];if(!meta)return;const now=new Date(),time=now.toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'}),timestamp=`${selectedDate}T${String(now.getHours()).padStart(2,'0')}:${String(now.getMinutes()).padStart(2,'0')}:${String(now.getSeconds()).padStart(2,'0')}`;state.healthLog.push({id:crypto.randomUUID(),date:selectedDate,statusV8:status,time,timestamp});state.painLog.push({id:crypto.randomUUID(),date:selectedDate,value:meta.pain,time,timestamp,source:'status'});save(`${meta.label} saved to your recovery record`);renderStatus();if(status==='critical')$('critical-dialog').showModal()}
function renderToday(){const d=pathwayDay(selectedDate);$('recovery-day').textContent=d&&d>=1?`Recovery Day ${d}`:'Pre-discharge';$('today-title').textContent=selectedDate===localDate()?`${timeGreeting()}, ${state.profile.firstName}`:formatDate(selectedDate,{weekday:'long'});$('today-date').textContent=`${formatDate(selectedDate,{month:'long',day:'numeric',year:'numeric'})} · ${state.profile.procedure}`;renderDateStrip();renderStatus();renderTimeline();renderProgress();$('doctor-questions').value=state.questions||''}
function callCareTeam(){const n=(state.care.phone||'').replace(/[^+\d]/g,'');if(n){location.href=`tel:${n}`;return}navigate('care-team');notice('Add your care team phone number first.')}
function renderCare(){const has=!!(state.care.teamName&&state.care.phone);$('care-contact-card').hidden=!has;$('care-now').hidden=!has;$('care-empty').hidden=has;$('care-edit-toggle').textContent=has?'Edit care team':'Add care team';$('care-name').textContent=state.care.teamName||'';$('care-phone').textContent=state.care.phone||'';const f=$('care-form');f.elements.teamName.value=state.care.teamName||'';f.elements.phone.value=state.care.phone||'';$('care-edit-wrap').hidden=true}
function renderTrend(){const list=$('trend-list'),graph=$('trend-graph'),empty=$('trend-empty');list.replaceChildren();graph.replaceChildren();const pains=[...state.painLog].sort((a,b)=>(a.timestamp||'').localeCompare(b.timestamp||'')).slice(-10);empty.hidden=!!pains.length;if(!pains.length)return;const w=300,h=90,pad=14,pts=pains.map((e,i)=>({x:pains.length===1?w/2:pad+i*((w-pad*2)/(pains.length-1)),y:pad+(Math.max(0,Math.min(10,e.value))/10)*(h-pad*2),e}));graph.innerHTML=`<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="Pain trend"><path d="${pts.map((p,i)=>`${i?'L':'M'}${p.x},${p.y}`).join(' ')}" fill="none" stroke="#405E78" stroke-width="3"/>${pts.map(p=>`<circle cx="${p.x}" cy="${p.y}" r="5" fill="#6F8FAF"/>`).join('')}</svg>`;[...pains].reverse().forEach(e=>{const row=document.createElement('div');row.className='trend-entry';row.innerHTML=`<span class="trend-dot" style="background:#6F8FAF"></span><div><strong>Pain ${e.value}/10</strong><small>${formatDate(e.date,{month:'short',day:'numeric'})}</small></div><time>${e.time||''}</time>`;list.append(row)})}
function renderPhotos(){const wrap=$('photo-journal');wrap.replaceChildren();state.photos.forEach(p=>{const d=document.createElement('div');d.className='photo-entry';const img=document.createElement('img');img.src=p.data;img.alt=`Wound journal photo from ${p.date}`;const del=document.createElement('button');del.type='button';del.textContent='×';del.onclick=()=>{state.photos=state.photos.filter(x=>x.id!==p.id);save('Photo removed');renderPhotos()};d.append(img,del);wrap.append(d)})}
function renderProfile(){const f=$('profile-form');f.elements.firstName.value=state.profile.firstName;f.elements.procedure.value=state.profile.procedure;f.elements.dischargeDate.value=state.profile.dischargeDate;renderTrend();renderPhotos()}
function navigate(route){if(!state.onboarded)return;routes.forEach(id=>$(id).hidden=id!==route);document.querySelectorAll('.bottom-nav button').forEach(b=>b.dataset.route===route?b.setAttribute('aria-current','page'):b.removeAttribute('aria-current'));if(route==='today')renderToday();if(route==='care-team')renderCare();if(route==='profile')renderProfile();window.scrollTo(0,0)}
function completeSetup(){state.onboarded=true;selectedDate=localDate();save();showScreen('workspace');navigate('today')}
function shareSummary(){const recent=[...state.healthLog].filter(x=>x.statusV8).slice(-5),done=Object.values(state.completed).filter(Boolean).length,text=[`Aftercare progress for ${state.profile.firstName}`,`Procedure: ${state.profile.procedure}`,`Discharge: ${state.profile.dischargeDate}`,`Completed items: ${done}`,recent.length?'Recent check-ins:':'',...recent.map(e=>`${e.date} ${e.time}: ${statusMap[e.statusV8]?.label||e.statusV8}`),state.questions?`Questions for doctor: ${state.questions}`:''].filter(Boolean).join('\n');if(navigator.share)navigator.share({title:'Aftercare Progress',text}).catch(()=>{});else{navigator.clipboard?.writeText(text);notice('Progress summary copied')}}
$('start').onclick=()=>{showScreen('setup');showWizard(1)};
$('procedure-form').onsubmit=e=>{e.preventDefault();const f=e.currentTarget,firstName=f.elements.firstName.value.trim(),procedure=f.elements.procedure.value,dischargeDate=f.elements.dischargeDate.value;if(!firstName||!procedure||!Number.isFinite(calendarDay(dischargeDate)))return notice('Complete all procedure details.');state.profile={firstName,procedure,dischargeDate};showWizard(2)};
$('wizard-add-med').onclick=()=>openItemDialog('medication',true);$('wizard-add-care').onclick=()=>openItemDialog('care',true);$('to-care').onclick=()=>showWizard(3);$('skip-meds').onclick=()=>showWizard(3);$('skip-care').onclick=completeSetup;document.querySelectorAll('[data-wizard-back]').forEach(b=>b.onclick=()=>showWizard(Number(b.dataset.wizardBack)));$('complete-setup').onclick=completeSetup;
$('add-item').onclick=()=>openItemDialog('medication',false);$('item-form').elements.type.onchange=updateDoseVisibility;$('item-form').onsubmit=e=>{e.preventDefault();const f=e.currentTarget,d=Object.fromEntries(new FormData(f)),editId=f.dataset.editId,type=d.type,item={id:editId||crypto.randomUUID(),type,title:d.title.trim(),dose:type==='medication'?(d.dose||'').trim():'',startDate:d.startDate,time:d.time,frequency:d.frequency};if(!item.title||!Number.isFinite(calendarDay(item.startDate)))return notice('Complete the required fields.');if(editId){const i=state.items.findIndex(x=>x.id===editId);if(i>=0)state.items[i]=item}else state.items.push(item);$('item-dialog').close();renderSetupLists();if(f.dataset.wizard!=='1'){selectedDate=item.startDate;save('Item saved');renderToday()}};
$('log-prn').onclick=()=>{const f=$('prn-form');f.reset();f.elements.time.value=new Date().toTimeString().slice(0,5);$('prn-dialog').showModal()};$('prn-form').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));state.prnLog.push({id:crypto.randomUUID(),date:selectedDate,time:d.time,title:d.title.trim(),dose:(d.dose||'').trim()});save('As-needed medication logged');$('prn-dialog').close();renderToday()};
document.querySelectorAll('[data-status]').forEach(b=>b.onclick=()=>logStatus(b.dataset.status));$('add-vitals').onclick=()=>{$('vitals-form').reset();$('vitals-dialog').showModal()};$('vitals-form').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));if(!d.temperature&&!d.bloodPressure&&!d.pulse)return notice('Enter at least one value.');const now=new Date();state.vitals.push({id:crypto.randomUUID(),date:selectedDate,time:now.toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'}),...d});save('Vitals saved');$('vitals-dialog').close()};
$('today-call').onclick=callCareTeam;$('help-call').onclick=callCareTeam;$('critical-care').onclick=()=>{$('critical-dialog').close();callCareTeam()};$('care-now').onclick=callCareTeam;$('care-edit-toggle').onclick=()=>{$('care-edit-wrap').hidden=!$('care-edit-wrap').hidden};$('care-form').onsubmit=e=>{e.preventDefault();state.care={teamName:e.currentTarget.elements.teamName.value.trim(),phone:e.currentTarget.elements.phone.value.trim()};if(!state.care.teamName||!state.care.phone)return notice('Enter a care team name and phone number.');save('Care team saved');renderCare()};
$('save-questions').onclick=()=>{state.questions=$('doctor-questions').value.trim();save('Questions saved')};$('share-progress').onclick=shareSummary;$('wound-photo').onchange=e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>3_000_000)return notice('Please choose a photo under 3 MB.');const reader=new FileReader();reader.onload=()=>{state.photos.push({id:crypto.randomUUID(),date:localDate(),data:reader.result});save('Photo saved on this device');renderPhotos()};reader.readAsDataURL(file)};
$('profile-form').onsubmit=e=>{e.preventDefault();const f=e.currentTarget,firstName=f.elements.firstName.value.trim(),procedure=f.elements.procedure.value.trim(),dischargeDate=f.elements.dischargeDate.value;if(!firstName||!procedure||!Number.isFinite(calendarDay(dischargeDate)))return notice('Complete all profile fields.');state.profile={firstName,procedure,dischargeDate};save('Profile updated');renderProfile()};
document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>navigate(b.dataset.route));document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());
if(state.onboarded){showScreen('workspace');navigate('today')}else showScreen('welcome');
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));